export const AUDIO_CONFIG = {
  MAIN_VOLUME: 0.4,
  REVERB_DURATION: 2.0,
  REVERB_WET_GAIN: 0.25,
  COMPRESSOR_THRESHOLD: -14,
  COMPRESSOR_KNEE: 30,
  COMPRESSOR_RATIO: 12,
  COMPRESSOR_ATTACK: 0.003,
  COMPRESSOR_RELEASE: 0.25,
  STRUM_DELAY_STEP: 0.08,
  AUDIO_RELEASE_TAIL: 1.4,
} as const;
