export const AUDIO_CONFIG = {
  A4_FREQ: 440,
  A4_MIDI_NOTE: 69,

  MAIN_VOLUME_DB: -8,
  REVERB_DURATION: 1.2,
  REVERB_WET_GAIN: 0.2,

  COMPRESSOR_THRESHOLD: -14,
  COMPRESSOR_KNEE: 30,
  COMPRESSOR_RATIO: 12,
  COMPRESSOR_ATTACK: 0.003,
  COMPRESSOR_RELEASE: 0.25,

  STRUM_DELAY_STEP: 0.06,
  AUDIO_RELEASE_TAIL: 0.6,

  SYNTH_HARMONICITY: 1.5,
  SYNTH_MODULATION_INDEX: 2.5,
  ENV_ATTACK: 0.004,
  ENV_DECAY: 0.12,
  ENV_SUSTAIN: 0.28,
  ENV_RELEASE: 0.5,
} as const;
