export const STORAGE_KEYS = {
  CHORD_LIST: 'CHORD_LAB_LIST_V4',
  GROUPS: 'CHORD_LAB_GROUPS',
  CURR_NAME: 'CHORD_LAB_CURR_NAME_V1',
  CURR_FRETS: 'CHORD_LAB_CURR_FRETS_V1',
  CURR_FCOUNT: 'CHORD_LAB_CURR_FCOUNT_V1',
  CURR_CAPO: 'CHORD_LAB_CURR_CAPO_V1',
  CURR_ROOT_MARK: 'CHORD_LAB_CURR_ROOT_MARK_V1',
  CURR_USE_FLAT: 'CHORD_LAB_CURR_USE_FLAT_V1',
  EDITING_ID: 'CHORD_LAB_EDITING_ID',
  CURR_GROUP_ID: 'CHORD_LAB_CURR_GROUP_ID_V1',
  CURR_STRINGS: 'CHORD_LAB_CURR_STRINGS_V1',
} as const;
