import { GrammarTemplate } from './chordEngine';

export const GRAMMAR_TEMPLATES: GrammarTemplate[] = [
  {
    suffix: '',
    category: 'triad',
    baseWeight: 100,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [1, 3, 5, 6, 8, 10, 11],
  },
  {
    suffix: 'm',
    category: 'triad',
    baseWeight: 100,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 3, role: 'third_minor', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [1, 4, 5, 6, 8, 10, 11],
  },
  {
    suffix: 'dim',
    category: 'triad',
    baseWeight: 70,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 3, role: 'third_minor', confidence: 'core' },
      { interval: 6, role: 'fifth_dim', confidence: 'core' },
    ],
    conflicts: [4, 7, 8, 10, 11],
  },
  {
    suffix: 'aug',
    category: 'triad',
    baseWeight: 70,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 8, role: 'fifth_aug', confidence: 'core' },
    ],
    conflicts: [3, 6, 7, 10, 11],
  },
  {
    suffix: 'sus4',
    category: 'sus',
    baseWeight: 80,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 5, role: 'sus4', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [3, 4],
  },
  {
    suffix: 'sus2',
    category: 'sus',
    baseWeight: 80,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 2, role: 'sus2', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [3, 4],
  },
  {
    suffix: '5',
    category: 'power',
    baseWeight: 50,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 7, role: 'fifth_perfect', confidence: 'core' },
    ],
    conflicts: [1, 2, 3, 4, 5, 6, 8, 9, 10, 11],
  },
  {
    suffix: '6',
    category: 'triad',
    baseWeight: 110,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 9, role: 'sixth', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [3, 10, 11],
  },
  {
    suffix: 'm6',
    category: 'triad',
    baseWeight: 110,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 3, role: 'third_minor', confidence: 'core' },
      { interval: 9, role: 'sixth', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [4, 10, 11],
  },
  {
    suffix: 'add9',
    category: 'triad',
    baseWeight: 100,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 2, role: 'ninth', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [3, 10, 11],
  },
  {
    suffix: 'madd9',
    category: 'triad',
    baseWeight: 100,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 3, role: 'third_minor', confidence: 'core' },
      { interval: 2, role: 'ninth', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [4, 10, 11],
  },
  {
    suffix: 'add11',
    category: 'triad',
    baseWeight: 105,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 5, role: 'eleventh', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [3, 10, 11],
  },
  {
    suffix: 'madd11',
    category: 'triad',
    baseWeight: 105,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 3, role: 'third_minor', confidence: 'core' },
      { interval: 5, role: 'eleventh', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [4, 10, 11],
  },
  {
    suffix: '6/9',
    category: 'triad',
    baseWeight: 120,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 9, role: 'sixth', confidence: 'core' },
      { interval: 2, role: 'ninth', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [3, 10, 11],
  },
  {
    suffix: 'm6/9',
    category: 'triad',
    baseWeight: 120,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 3, role: 'third_minor', confidence: 'core' },
      { interval: 9, role: 'sixth', confidence: 'core' },
      { interval: 2, role: 'ninth', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [4, 10, 11],
  },
  {
    suffix: '7',
    category: 'seventh',
    baseWeight: 130,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [3, 11],
  },
  {
    suffix: 'Maj7',
    category: 'seventh',
    baseWeight: 130,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 11, role: 'seventh_major', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [3, 10],
  },
  {
    suffix: 'm7',
    category: 'seventh',
    baseWeight: 130,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 3, role: 'third_minor', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [4, 11],
  },
  {
    suffix: 'mMaj7',
    category: 'seventh',
    baseWeight: 120,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 3, role: 'third_minor', confidence: 'core' },
      { interval: 11, role: 'seventh_major', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [4, 10],
  },
  {
    suffix: 'm7b5',
    category: 'seventh',
    baseWeight: 120,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 3, role: 'third_minor', confidence: 'core' },
      { interval: 6, role: 'fifth_dim', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
    ],
    conflicts: [4, 7, 11],
  },
  {
    suffix: 'dim7',
    category: 'seventh',
    baseWeight: 120,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 3, role: 'third_minor', confidence: 'core' },
      { interval: 6, role: 'fifth_dim', confidence: 'core' },
      { interval: 9, role: 'seventh_dim', confidence: 'core' },
    ],
    conflicts: [4, 7, 10, 11],
  },
  {
    suffix: 'dimMaj7',
    category: 'seventh',
    baseWeight: 115,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 3, role: 'third_minor', confidence: 'core' },
      { interval: 6, role: 'fifth_dim', confidence: 'core' },
      { interval: 11, role: 'seventh_major', confidence: 'core' },
    ],
    conflicts: [4, 10],
  },
  {
    suffix: '7sus4',
    category: 'sus',
    baseWeight: 110,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 5, role: 'sus4', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [3, 4],
  },
  {
    suffix: '7sus2',
    category: 'sus',
    baseWeight: 110,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 2, role: 'sus2', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [3, 4],
  },
  {
    suffix: '9',
    category: 'extended',
    baseWeight: 160,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
      { interval: 2, role: 'ninth', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [3, 11],
  },
  {
    suffix: 'Maj9',
    category: 'extended',
    baseWeight: 160,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 11, role: 'seventh_major', confidence: 'core' },
      { interval: 2, role: 'ninth', confidence: 'core' },
    ],
    optional: [
      { interval: 4, role: 'third_major', confidence: 'anchor' },
      { interval: 7, role: 'fifth_perfect', confidence: 'anchor' },
    ],
    conflicts: [3, 10],
  },
  {
    suffix: 'm9',
    category: 'extended',
    baseWeight: 160,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 3, role: 'third_minor', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
      { interval: 2, role: 'ninth', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [4, 11],
  },
  {
    suffix: 'mMaj9',
    category: 'extended',
    baseWeight: 165,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 3, role: 'third_minor', confidence: 'core' },
      { interval: 11, role: 'seventh_major', confidence: 'core' },
      { interval: 2, role: 'ninth', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [4, 10],
  },
  {
    suffix: 'm9b5',
    category: 'extended',
    baseWeight: 150,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 3, role: 'third_minor', confidence: 'core' },
      { interval: 6, role: 'fifth_dim', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
      { interval: 2, role: 'ninth', confidence: 'core' },
    ],
    conflicts: [4, 7, 11],
  },
  {
    suffix: '9sus4',
    category: 'sus',
    baseWeight: 150,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 5, role: 'sus4', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
      { interval: 2, role: 'ninth', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [3, 4],
  },
  {
    suffix: '11',
    category: 'extended',
    baseWeight: 170,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
      { interval: 5, role: 'eleventh', confidence: 'core' },
    ],
    optional: [
      { interval: 2, role: 'ninth', confidence: 'optional' },
      { interval: 7, role: 'fifth_perfect', confidence: 'anchor' },
    ],
    conflicts: [3],
  },
  {
    suffix: 'm11',
    category: 'extended',
    baseWeight: 170,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 3, role: 'third_minor', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
      { interval: 5, role: 'eleventh', confidence: 'core' },
    ],
    optional: [
      { interval: 2, role: 'ninth', confidence: 'optional' },
      { interval: 7, role: 'fifth_perfect', confidence: 'anchor' },
    ],
    conflicts: [4],
  },
  {
    suffix: '13',
    category: 'extended',
    baseWeight: 180,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
      { interval: 9, role: 'thirteenth', confidence: 'core' },
    ],
    optional: [
      { interval: 2, role: 'ninth', confidence: 'optional' },
      { interval: 4, role: 'third_major', confidence: 'anchor' },
      { interval: 7, role: 'fifth_perfect', confidence: 'anchor' },
    ],
    conflicts: [3],
  },
  {
    suffix: 'm13',
    category: 'extended',
    baseWeight: 185,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 3, role: 'third_minor', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
      { interval: 9, role: 'thirteenth', confidence: 'core' },
    ],
    optional: [
      { interval: 2, role: 'ninth', confidence: 'optional' },
      { interval: 7, role: 'fifth_perfect', confidence: 'anchor' },
    ],
    conflicts: [4],
  },
  {
    suffix: 'Maj13',
    category: 'extended',
    baseWeight: 180,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 11, role: 'seventh_major', confidence: 'core' },
      { interval: 9, role: 'thirteenth', confidence: 'core' },
    ],
    optional: [
      { interval: 2, role: 'ninth', confidence: 'optional' },
      { interval: 4, role: 'third_major', confidence: 'anchor' },
      { interval: 7, role: 'fifth_perfect', confidence: 'anchor' },
    ],
    conflicts: [3],
  },
  {
    suffix: '13sus4',
    category: 'sus',
    baseWeight: 190,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 5, role: 'sus4', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
      { interval: 9, role: 'thirteenth', confidence: 'core' },
    ],
    optional: [
      { interval: 2, role: 'ninth', confidence: 'optional' },
      { interval: 7, role: 'fifth_perfect', confidence: 'anchor' },
    ],
    conflicts: [3, 4],
  },
  {
    suffix: '7(#9)',
    category: 'altered',
    baseWeight: 150,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
      { interval: 3, role: 'ninth_sharp', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [11],
  },
  {
    suffix: '7(b9)',
    category: 'altered',
    baseWeight: 150,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
      { interval: 1, role: 'ninth_flat', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [11],
  },
  {
    suffix: '7(#5)',
    category: 'altered',
    baseWeight: 140,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
      { interval: 8, role: 'fifth_aug', confidence: 'core' },
    ],
    conflicts: [3, 7, 11],
  },
  {
    suffix: '7(b5)',
    category: 'altered',
    baseWeight: 140,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
      { interval: 6, role: 'fifth_dim', confidence: 'core' },
    ],
    conflicts: [3, 7, 11],
  },
  {
    suffix: 'Maj7(#5)',
    category: 'altered',
    baseWeight: 140,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 11, role: 'seventh_major', confidence: 'core' },
      { interval: 8, role: 'fifth_aug', confidence: 'core' },
    ],
    conflicts: [3, 7, 10],
  },
  {
    suffix: 'Maj7(b5)',
    category: 'altered',
    baseWeight: 140,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 11, role: 'seventh_major', confidence: 'core' },
      { interval: 6, role: 'fifth_dim', confidence: 'core' },
    ],
    conflicts: [3, 7, 10],
  },
  {
    suffix: '7(#11)',
    category: 'altered',
    baseWeight: 170,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
      { interval: 6, role: 'eleventh_sharp', confidence: 'core' },
    ],
    optional: [
      { interval: 7, role: 'fifth_perfect', confidence: 'anchor' },
      { interval: 2, role: 'ninth', confidence: 'optional' },
    ],
    conflicts: [3, 11],
  },
  {
    suffix: 'Maj7(#11)',
    category: 'altered',
    baseWeight: 170,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 11, role: 'seventh_major', confidence: 'core' },
      { interval: 6, role: 'eleventh_sharp', confidence: 'core' },
    ],
    optional: [
      { interval: 7, role: 'fifth_perfect', confidence: 'anchor' },
      { interval: 2, role: 'ninth', confidence: 'optional' },
    ],
    conflicts: [3, 10],
  },
  {
    suffix: '9(#11)',
    category: 'altered',
    baseWeight: 185,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
      { interval: 2, role: 'ninth', confidence: 'core' },
      { interval: 6, role: 'eleventh_sharp', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [3, 11],
  },
  {
    suffix: 'Maj9(#11)',
    category: 'altered',
    baseWeight: 185,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 11, role: 'seventh_major', confidence: 'core' },
      { interval: 2, role: 'ninth', confidence: 'core' },
      { interval: 6, role: 'eleventh_sharp', confidence: 'core' },
    ],
    optional: [{ interval: 7, role: 'fifth_perfect', confidence: 'anchor' }],
    conflicts: [3, 10],
  },
  {
    suffix: '13(#11)',
    category: 'altered',
    baseWeight: 195,
    required: [
      { interval: 0, role: 'root', confidence: 'core' },
      { interval: 4, role: 'third_major', confidence: 'core' },
      { interval: 10, role: 'seventh_minor', confidence: 'core' },
      { interval: 9, role: 'thirteenth', confidence: 'core' },
      { interval: 6, role: 'eleventh_sharp', confidence: 'core' },
    ],
    optional: [
      { interval: 2, role: 'ninth', confidence: 'optional' },
      { interval: 7, role: 'fifth_perfect', confidence: 'anchor' },
    ],
    conflicts: [3],
  },
];
